/*
 *  ----------------------------------------------------------------------------------------------->
 *  Licença    : MIT - Copyright 2019 Viniciusalopes (Vovolinux) <suporte@vovolinux.com.br>
 *  Criado em  : 11/10/2020 18:43:27 
 *  Instituição: FACULDADE SENAI FATESG
 *  Curso      : Análise e Desenvolvimento de Sistemas - Módulo 3 - 2020/2
 *  Disciplina : PP - Padrões de Projeto
 *  Aluno      : Vinicius Araujo Lopes
 *  Projeto    : SINGLETON / DECORATOR / TEMPLATE / FACTORY
 *  Exercício  : Colaboradores de uma empresa
 *  ------------------------------------------------------------------------------------------------
 *  Tela para cadastro de Colaborador.
 *  -----------------------------------------------------------------------------------------------| 
 */
package br.com.vinicius.app;

import br.com.vinicius.bll.BllColaborador;
import br.com.vinicius.bll.BllHabilidade;
import br.com.vinicius.bll.BllSetor;
import static br.com.vinicius.generic.app.AppDesktopMensagem.mensagem;
import static br.com.vinicius.generic.app.AppDesktopMensagem.mensagemErro;
import static br.com.vinicius.generic.app.AppFactory.getModal;
import br.com.vinicius.generic.app.AppIModal;
import br.com.vinicius.generic.app.AppSimpleForm;
import br.com.vinicius.model.Colaborador;
import br.com.vinicius.model.Setor;

/**
 *
 * @author vovostudio
 */
public class AppJDialogColaborador extends javax.swing.JDialog implements AppIModal {

    //--- ATRIBUTOS ------------------------------------------------------------------------------->
    //
    private Colaborador colaborador;
    private String action = "add";
    private String complement = "";

    //--- FIM ATRIBUTOS ---------------------------------------------------------------------------|
    //
    @Override
    public void setObject(Object object) throws Exception {
        colaborador = (Colaborador) object;
    }

    @Override
    public void setFriendlyName(String friendlyName) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setVisible(boolean b) {
        try {
            fillComboBoxSetores();
            if (colaborador.getId() > 0) {
                action = "update";
                complement = "  [ID:" + colaborador.getId() + "]";
                jTextFieldColaborador_id.setText(colaborador.getId() + "");
                jTextFieldColaborador_nome.setText(colaborador.getNome());
                jComboBoxSetores.setSelectedItem(BllSetor.getSetor(colaborador.getSetor_id()).getNome());
            }
            this.setTitle(((action.equals("add")) ? "Incluir" : "Editar") + " cadastro de Colaborador " + complement);
            super.setVisible(b);

            jTextFieldColaborador_nome.requestFocus();
        } catch (Exception e) {
            mensagemErro(e);
        }
    }

    /**
     * Atualiza os itens do ComboBox
     *
     * @throws Exception
     */
    private void fillComboBoxSetores() throws Exception {
        jComboBoxSetores.removeAllItems();
        for (Setor setor : BllSetor.getSetores(1)) {
            jComboBoxSetores.addItem(setor.getNome());
        }
        jComboBoxSetores.setSelectedIndex(-1);
    }

    /**
     * Creates new form AppJDialogColaborador
     */
    public AppJDialogColaborador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jTextFieldColaborador_id = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldColaborador_nome = new javax.swing.JTextField();
        jComboBoxSetores = new javax.swing.JComboBox<>();
        jButtonCadastroSetores = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel7.setText("ID");

        jTextFieldColaborador_id.setEditable(false);
        jTextFieldColaborador_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldColaborador_id.setFocusable(false);

        jLabel11.setText("Nome do Colaborador");

        jButtonCadastroSetores.setText("+");
        jButtonCadastroSetores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroSetoresActionPerformed(evt);
            }
        });

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jLabel6.setText("Setor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldColaborador_id, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jTextFieldColaborador_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxSetores, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCadastroSetores))))
                    .addComponent(jButtonOK, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldColaborador_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldColaborador_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSetores, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCadastroSetores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOK)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        try {
            if (jComboBoxSetores.getSelectedIndex() == -1) {
                throw new Exception("Selecione um setor.");
            }
            Colaborador colab = new Colaborador(
                    colaborador.getId(),
                    jTextFieldColaborador_nome.getText(),
                    BllSetor.getSetor(jComboBoxSetores.getSelectedItem() + "", 1).getId(),
                    BllHabilidade.getHabilidadesOrigem(1)
            );
            if (action.equals("add")) {
                BllColaborador.add(colab);
            } else {
                BllColaborador.update(colab);
            }
            mensagem("Sucesso!", "Colaborador " + ((action.equals("add")) ? "incluído" : "editado") + " com sucesso!");
            this.dispose();

        } catch (Exception e) {
            mensagemErro(e);
        }
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonCadastroSetoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroSetoresActionPerformed
        try {
            getModal(new Setor(1), "Setor", new AppSimpleForm(null, true));
            fillComboBoxSetores();
        } catch (Exception e) {
            mensagemErro(e);
        }
    }//GEN-LAST:event_jButtonCadastroSetoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppJDialogColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppJDialogColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppJDialogColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppJDialogColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AppJDialogColaborador dialog = new AppJDialogColaborador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastroSetores;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JComboBox<String> jComboBoxSetores;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextFieldColaborador_id;
    private javax.swing.JTextField jTextFieldColaborador_nome;
    // End of variables declaration//GEN-END:variables
}
